#pragma once

enum BGMCode
{
	BGM_TITLE,
	BGM_STAGE1,
	BGM_BOSS1,
	BGM_GAMECLEAR,
	BGM_GAMEOVER
};
enum SECode{
	SE_ATTACK_REFLECTION,
	SE_ATTACK_THROUGH,
	SE_ATTACK_HEAVY,
	SE_WALL_CONTACT,//プレイヤーの球が壁にぶつかる
	SE_FIREBER,
	SE_DIVEWATER,
	SE_INSIDEWATER,
	SE_PLAYER_DAMAGE,
	SE_PLAYER_DIE,
	SE_JUMP,
	SE_HEAL,
	SE_HEAVY,
	SE_ICE,
	SE_FIRE,//フレイムピラーの音
	SE_FIRE_SPIDERWEB,//蜘蛛の巣
	SE_FIRE_ICE,//氷
	SE_BURNER,
	SE_ENEMY_ATTACK01,//通常
	SE_ENEMY_ATTACK02,//大砲
	SE_ENEMY_DAMAGE,
	SE_ENEMY_DIE,
	SE_BOSS_ATTACK01,//剣を振り下ろす
	SE_BOSS_ATTACK02,//ジャンプ斬り
	SE_BOSS_ATTACK03,//盾突進1
	SE_BOSS_ATTACK04,//盾突進2
	SE_BOSS_JUMP,
	SE_BOSS_DAMAGE,
	SE_BOSS_SHIELD,
	SE_SELECT_CHANGE,
	SE_SELECT_OK,


	
};
